/// Flutter icons EFishFarmApp
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EFishFarmApp
///      fonts:
///       - asset: fonts/EFishFarmApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EFishFarmApp {
  EFishFarmApp._();

  static const _kFontFam = 'EFishFarmApp';
  static const String? _kFontPkg = null;

  static const IconData farm_logo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData company_logo = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
